title: "Dante Trabassi"
description: >
  AI & ML Scientist | Explainable AI for Clinical Movement Analysis  
  PhD in Neuroscience @Sapienza | Parkinson’s Disease, EMG, Wearables

theme: jekyll-theme-minimal
logo: /assets/img/profile.png

show_downloads: false
